from abaqusConstants import NODAL, ELEMENT_NODAL, INTEGRATION_POINT, CYLINDRICAL
from abaqusConstants import MISES, PRESS, MAGNITUDE, TRESCA, INV3, MAX_PRINCIPAL,MID_PRINCIPAL, MIN_PRINCIPAL
from abaqusConstants import MAX_INPLANE_PRINCIPAL, MIN_INPLANE_PRINCIPAL, OUTOFPLANE_PRINCIPAL

abaqus_constants = {'CYLINDRICAL': CYLINDRICAL}

output_positions = {
    'NODAL': NODAL,
    'ELEMENT_NODAL': ELEMENT_NODAL,
    'INTEGRATION_POINT': INTEGRATION_POINT}

invariants = {
    'MISES': MISES,
    'PRESS': PRESS,
    'MAGNITUDE': MAGNITUDE,
    'TRESCA': TRESCA,
    'INV3': INV3,
    'MAX_PRINCIPAL': MAX_PRINCIPAL,
    'MID_PRINCIPAL': MID_PRINCIPAL,
    'MIN_PRINCIPAL': MIN_PRINCIPAL,
    'MAX_INPLANE_PRINCIPAL': MAX_INPLANE_PRINCIPAL,
    'MIN_INPLANE_PRINCIPAL': MIN_INPLANE_PRINCIPAL,
    'OUTOFPLANE_PRINCIPAL': OUTOFPLANE_PRINCIPAL
}

abaqus_constants.update(output_positions)
abaqus_constants.update(invariants)
